### ISSUE TITLE
Lag, disconnect, temporary freeze and bouncing

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#286] opened 2019-04-21 18:06 UTC
Didnt have this problem before but now happens every game, few others on discord report same problem. I checked ping and fps and get around 60 fps and 144 ms not sure what is causing the issue.

Twisted had disconnect too here : https://youtu.be/4b0baMgQosA?t=1215

**Comment by trevorhackman** [comment] 2019-04-22 23:13
It seems to happen to everyone on the server simultaneously, https://clips.twitch.tv/VainPlausibleCamelAMPEnergyCherry
This clip was taken at about 7:10pm 4/22/2019

Can always almost immediately reconnect

**Comment by Welcius** [comment] 2019-04-23 17:43
I have been suffering this problem as well, you can see more affected people on this forum thread:
https://onehouronelife.com/forums/viewtopic.php?id=6050

**Comment by dogwolf12** [comment] 2019-04-24 12:09
Me too - lots of login fails before finally getting in and playing a very patchy life with many disconnects

**Comment by BlueDiamondAvatar** [comment] 2019-04-24 14:04
I have a very stable internet connection, and have never experienced frequent disconnects before.  The last week, it's been happening at least three to four times a life, and I'm seeing lots of people in game, experiencing the same problem.  Lots of eve families are dying off because the last girl disconnects and dies, rather than player mistakes or a bad starting spot, etc.

**Comment by TwistedHBG** [comment] 2019-04-27 12:02
My lives have had either no disconnects, or many disconnects, so it doesn't seem to be a consistent issue. One of my commenters pointed out that the disconnects seem to happen when a person near you dies. and looking at my recordings that does appear to be correct. ~~It's likely related to the grave name change.~~ As Dodg-e pointed out it's probably related to property gates, that would explain why deaths sometimes disconnect and sometimes don't.

**Comment by Dodg-e** [comment] 2019-04-28 16:46
Could be related to property gates that need to be checked each time someone dies

**Comment by jasonrohrer** [comment] 2019-04-30 19:02
Any more info here?  Are you a co-owner of the gate when someone dies?

**Comment by TwistedHBG** [comment] 2019-04-30 19:07
No, the disconnect happens even when you don't own any gates.

**Comment by jasonrohrer** [comment] 2019-04-30 20:22
Can you guys mess around as twins on a high-number server and see if you can come up with steps to reproduce?

I've been hammering on my test server, and I can't get gates to cause any disconnects.

I've tried having two players own 13 gates each, and some cross-ownership, but when one player dies, the code that is removing gate ownership is taking 0.00000 sec to run.

Also, from what I've seen, this disconnect issue is instant, and not just a server stall (where you bounce for a while).

Next time it happens to you, can you send me your stdout.txt?

**Comment by jasonrohrer** [comment] 2019-04-30 22:25
Okay, I was able to find the problem.  Rolling out a hot fix for this now.

**Closed as completed** 2019-04-30 22:29 UTC
