### ISSUE TITLE
NPCs not generating sometimes

### ISSUE THREAD

**Issue by luckyluckluc** [jasonrohrer/OneLife#328] opened 2019-06-04 20:41 UTC
is there some sort of bug where wildlife doesn't spawn? i've recently had two villages where there were no wildlife spawning. No mouflons, no snakes etc....

It is a small village and there is no way everysingle boar/snake/horse was consumed within a 1km radius

it isn't through player consumption
there is milkweed everywhere still
I'm quite certain the server isn't generating NPCs sometimes
even mosquitos are missing

if you want to see for yourself there is a snow family that is making a new village at this moment. they can't get a sheep up and I looked around and there are no generated NPCs such as snakes,horses, mosquitos, mouflons, wolves, boars, etc....

**Comment by jasonrohrer** [comment] 2019-06-12 17:58
Pretty sure this was caused by #332 
Fixed now.

**Closed as completed by jasonrohrer** 2019-06-12 17:58 UTC

**Comment by luckyluckluc** [comment] 2019-06-13 15:54
As of today, I am still seeing this issue

**Comment by luckyluckluc** [comment] 2019-06-13 15:55
Was born into Stark family a few minutes ago. All the same variables as mentioned above

**Comment by AlecYawata** [comment] 2019-06-14 00:01
> Pretty sure this was caused by #332
> Fixed now.

Yes, that fixed now.

@luckyluckluc 
But, its not released.
Wait next update.
