### ISSUE TITLE
DC for flooding when posse

### ISSUE THREAD

**Issue by teliot** [jasonrohrer/OneLife#830] opened 2023-06-11 19:32 UTC
When chasing people in a posse you can trigger the server DCing you for flooding with too many actions.

**Comment by jasonrohrer** [comment] 2023-06-21 17:04
Hmm... is there a video somewhere of this happening?

I'm guessing that the server isn't forcing you to disconnect in this case... there's no way you're manually sending 80 move messages in 5 seconds, even if you're running with a posse.

But rather, if you're running with a huge crowd of people, you're getting lots of move updates from all of them.  This might be filling up your incoming network queue on your client, causing it to drop some data, resulting in incomplete information from the server, in which case, your client will receive a chopped-off message, and disconnect.

This probably has to do with how much traffic your network connection can handle.

**Comment by TwistedHBG** [comment] 2023-06-21 21:36
https://youtu.be/CbVrkBrNQ8Y?t=873

and then a few seconds later - https://youtu.be/CbVrkBrNQ8Y?t=881

**Comment by jasonrohrer** [comment] 2023-06-22 15:07
Welp, that definitely sucks...

**Comment by jasonrohrer** [comment] 2023-06-22 22:02
We did a massive stress-test today with a dozen or more people joining posses like crazy, but we were unable to reproduce this issue.

**Comment by jasonrohrer** [comment] 2023-06-26 14:54
I'm going to close this for now, since it seems like the DC isn't necessarily related to being in a posse.

Please re-open if anyone gets more information about this.

**Closed as completed** 2023-06-26 17:20 UTC
