### ISSUE TITLE
DB corruption

### ISSUE THREAD

**Issue by FlorianLudwig** [jasonrohrer/OneLife#22] opened 2018-04-02 19:23 UTC
For my community server it seems the database got corrupted. I got a lot of funny business going on, like:

Wells in baskets
![screenshot from 2018-04-02 21-08-56](https://user-images.githubusercontent.com/432263/38211568-30010cb4-36bb-11e8-8b27-a5b7f1cce41e.png)

Berry bushes in backpacks
![screenshot from 2018-04-02 13-24-04](https://user-images.githubusercontent.com/432263/38211581-3884f1ac-36bb-11e8-9b4a-6f37f6e0c645.png)

Friendly (as in not moving) bears
![screenshot from 2018-04-02 12-57-05](https://user-images.githubusercontent.com/432263/38211604-4b7b23da-36bb-11e8-8550-a1aba31132d2.png)

At some point I had a berry bush turn into a bowl of dough when I picked a berry from the bush. (but cannot reproduce it anymore)

Also I am pretty sure I have had rattle snake skins **before** i updated the server.

## Fixing the bug
It seems to be related to have a server without the 71 content update connecting to a 67 server. Not sure how this could make things go wrong but it does correlate
## Recovery
Any ideas how to cleanup the db?

**Comment by FlorianLudwig** [comment] 2018-04-02 19:54
This seems to affect other community servers as well: 

> yay new update with horses, cactus ,and snakes.  so to get a snake you pick a berry, for a cactus pick a berry from snake! and to get a dead tree pick all the berries off the cactus! HAHAHA i love new patches! and now the chill server crashes, joy that's what i get for wanting to see the desert and horses.
-- http://onehouronelife.com/forums/viewtopic.php?pid=5856#p5856

**Comment by jasonrohrer** [comment] 2018-04-02 20:53
I'm guessing that this is caused by you NOT updating your client along with your server.

The client won't update if useCustomServer is set, so it will fall out of sync with the server.  Disable it in your client to get the update.

Note that this behavior will be improved in the next client update.  The client will now complain if its version does not match the version of the server that you're trying to connect to.

Closing this for now.  Please open a new one if the issue persists after updating your client.

**Closed as completed** 2018-04-02 20:54 UTC

**Comment by FlorianLudwig** [comment] 2018-04-06 20:34
I still believe there is more to it. For two reasons:

a) I could ride horses before. So if the client wasn't up to date there wouldn't be horses. And if the server wasn't up to date, what was I riding and how was i moving so fast from the server points of view?

b) Now I even updated client and server to 73. This means we got version number checks! So this cannot be happening anymore, right?
![screenshot from 2018-04-06 22-31-19](https://user-images.githubusercontent.com/432263/38443055-a5dffc42-39ea-11e8-9281-1aba8e1269d1.png)

Well, I am bear.
