### ISSUE TITLE
Babies should follow their moms

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLife#532] opened 2020-02-05 20:36 UTC
The hierarchy system in its current form is basically unusable due to the fact you need to actively hold a popularity contest standing around begging or asking people to follow you. Unless you basically constantly have people asking to follow or opt in to this system it basically cannot and will not work. 

Instead lets do the opposite and start each lineage with the system in place and force players who don't want to be a part of it to opt out. Basically every time a player is born they follow their mother who followed their mother, which means unless mom bows out the system starts in a matriarchy. 

This allows the system to actually exist without constantly needing to beg people to join and the hierarchy won't die every generation and instead will naturally keep going unless a player opts out and no one rejoins the main group.  

Without even thinking about all the goofy title stuff this refines the system down to something more like "Grandma is asking for someone to get kindling." which is basically the mom telling everyone else what is needed. 

ALSO: before I forget, I think the order message should be placed somewhere else on the screen or maybe stay up until you do something like /clear order because it's really easy to miss something like that due to the length of time it sticks around.

**Comment by jasonrohrer** [comment] 2020-02-05 21:18
Well, you could auto-follow mom UNLESS she is already following someone other than her mom, right?

I mean, if she has picked her own leader, you should also follow that leader (as it currently works) instead of following her.


This is also why it won't necessarily die every generation, because babies auto-follow their mom's leaders.

If the old leader picks a new one before dying, all of the followers will be inherited.

So keeping it going doesn't require action from everyone.  Just from the leaders to pick an heir.


Really, the leadership system is supposed to be something separate from the family structure, and not just a mirror of it...

**Comment by jasonrohrer** [comment] 2020-02-05 21:23
Anyway, auto-following a leaderless mom would certainly help to boostrap things, and make leadership the default state generally.

But beyond that, it should work the way it currently does, where you inherit mom's leaders.

So in a 0-leader situation, the next baby born follows Mom A, as do the other babies born to her.

Then when a grandbaby is born to Mom B (Mom A's child), the grandbaby also follows Mom A.  Same with g-g-babies, they all follow Mom A.

Mom A then decides what to do with that power.  If Mom A picks no heir before dying, it goes back to a leaderless state for a bit, and then starts over with new babies following their moms.


So it will bootstrap over and over, and people can decide for themselves if they want to keep it going each time.

But we don't automatically get a tree that mirrors the family structure.  There are instead a series of "default ladies" that rule for a bit and then die off.

**Comment by DougLefelhocz** [comment] 2020-02-05 23:37
> Re-reading this thread makes me realize that the recent update really should change so you automatically follow your MOTHER, not your mother's leader.

> It would work thematically (your interactions are with your mother and you can't pick a different leader until you are an adult)  and it provides a real in-game reason for mothers to care about their own children more than other people's kids.    By treating your kids properly and proving that you can be trusted, they might continue to follow you as an adult.   If your daughters follow you, then their children will become your subordinates as well, raising your rank.    If your daughters hate you, you will not rise up the hierarchy, because they will follow themselves or choose someone else when they get older.

[Original source](http://onehouronelife.com/forums/viewtopic.php?pid=83448#p83448)

**Comment by miskas9** [comment] 2020-02-06 17:07
I understand that you don't want the Public hierarchy to mirror the Family Hierarchy BUT we don have a family hierarchy in the first place. Could we get one? 
Like family orders and every kid auto following the immediate older sibling or his/her mom?
No extra titles need it.

**Comment by Kinrany** [comment] 2020-02-06 17:48
> I mean, if she has picked her own leader, you should also follow that leader (as it currently works) instead of following her.

Wait, why?

Suppose your mom decides to pick another leader right after you were born. It doesn't make much sense that you and your mom will have different leaders, does it?

> If the old leader picks a new one before dying, all of the followers will be inherited.

Turns out this is somewhat hard: the old leader must pick someone who is actually going to be a good leader and will in turn pick a new leader later. 

That said, making this easier will create a positive feedback loop: the more people can be good leaders, the easier it is to be a good leader and find another good leader.

Maybe https://github.com/jasonrohrer/OneLife/issues/534 will help: at least barons will immediately know when their king is dead.

**Comment by jasonrohrer** [comment] 2020-02-06 19:40
The WHY is so that not every family is an automatic leadership hierarchy.

If everyone auto-followed their mom, even if she was following someone else, then eventually the leadership tree would match the family tree.

As it stands, her lord is your lord.  Your mother isn't a political ruler IRL.  She is your mother.

The edge case where she switches leaders after giving birth is okay to leave as an edge case.  Your first loyalty is dyed in the wool, I guess.

**Comment by jasonrohrer** [comment] 2020-02-06 19:49
What if, when one of your leaders dies, you get a DING message about it, along with an arrow pointing toward their death location?

YOUR KING JAMES SMITH HAS DIED.
YOUR NEW PRIME LEADER IS BARON HARRY SMITH.

Action, the arrow should point to the new leader's position, I suppose.  Going to the grave has no immediate value.

So in this case, you'd see that DING message and then say, MY BARON, and get a map LEAD arrow to the location of your baron.

**Comment by jasonrohrer** [comment] 2020-02-06 19:49
Could also say YOU NOW HAVE NO LEADER in that case.

**Closed as completed** 2020-02-06 22:50 UTC

**Comment by Kinrany** [comment] 2020-02-07 09:11
> Your mother isn't a political ruler IRL.

But she is! She, you, and the rest of society agree that she [has power](https://en.wikipedia.org/wiki/Power_(social_and_political)) over your actions and carries responsibility for you.

At the very least she's someone who can give you orders. (Even though in the modern society she always has at least one leader: the husband in a patriarchal society, the boss at her workplace, or the president.)

> If everyone auto-followed their mom, even if she was following someone else, then eventually the leadership tree would match the family tree.

I'd say the leadership tree would *start* with the family tree.

The top levels of a hierarchy are by design more dynamic than the bottom levels. If even top levels of hierarchies are not different from the family tree, that's a bigger problem: that the leadership mechanics are not working and must be either fixed or scrapped.

> Action, the arrow should point to the new leader's position, I suppose. Going to the grave has no immediate value.

It has value when there's no new leader: when the king dies, his grave is a good place for all the barons to meet and to choose the new king
