### ISSUE TITLE
Tulestump + Basket not selectable

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#261] opened 2019-03-16 20:56 UTC
The previous mechanics where one creates a basket directly on the tule stumps is broken since the most recent update (v 2.11). The basket cannot be picked up any longer, thus rendering it useless

**Comment by JustinLove** [comment] 2019-03-17 01:04
This also affects horse carts. Someone said affecting something with fishing as well. Recent change to left click on containers.

**Comment by HimitsuGato** [comment] 2019-03-17 02:19
This probably should be in OnelifeData7. Duplicate of [#210 ](https://github.com/jasonrohrer/OneLifeData7/issues/210) over there but this one came first.

**Comment by jasonrohrer** [comment] 2019-03-18 05:37
No, this is a real client bug.... and a doozy...

Yes, the new right-click behavior broke it.

Unfortunately, I'm out of town for a week an unable to make any new client builds remotely.

So horse carts are unusable?  Sheesh, that's really bad....

**Closed as completed** 2019-03-25 18:24 UTC
