### ISSUE TITLE
Adjust server split triggers

### ISSUE THREAD

**Issue by path-to-aaru** [jasonrohrer/OneLife#1009] opened 2023-12-29 03:20 UTC
It's really nice when the game gets an influx of new players and we can get numbers like 80-90 on BS2. It's chaotic and fun and still manageable.

When they get upwards of 120+ then yes, it's too much and the server split makes sense. It comes with a couple issues, though. 

One being that it's always the new players who are funneled to server1 because the vets know how to connect to bs2. So they are dropped into wilderness with other people who don't know how to survive the wilderness, and that's probably the reason why the player count tends to fall sharply as soon as the server split happens.

The other issue is with the split still being triggered until bs2 hits low pop. It ends up so that the fun, healthy population of 80-90 is still around, but split into two underpopulated servers. At the time of writing this, the server has been split for hours and there are now only about 40 people on each server. 

That is lower than the pre-influx numbers on bs2, so it's like we got a player exodus instead of a new player wave. I suggest to remove the player splitting at something like 55 players on bs2. bs2 naturally has more players so it would probably occur at about 90 players online, which still leaves a healthy room for new logins before it might split again.

**Comment by DougLefelhocz** [comment] 2023-12-30 04:00
"One being that it's always the new players who are funneled to server1 because the vets know how to connect to bs2."

There do exist some vets that deliberately connect to s1 during this time also.  I've seen other PXChat users, and I even managed to get three latex buckets, a full palm oil bucket, a tomato, and a pepper all from one tan who wasn't using PXChat on s1 earlier tonight without any paper, just touching what I wanted (I wouldn't expect a new player to know that exactly 6 palm oil bowls go in a bucket or the rubber tree slash).  I don't know the ratio though, of course.

There have existed server1 towns making it to newcomen stage every day so far this week.  Soupir family started a few hours before the split, but lasted [34 generations](http://lineage.onehouronelife.com/server.php?action=character_page&id=10040819).  Earlier this morning, there was a message on PXChat by Clay that they needed kerosene, an engine, and a pump valve!  [Kaltman](http://lineage.onehouronelife.com/server.php?action=character_page&id=10047536) and [Hohenwarter](http://lineage.onehouronelife.com/server.php?action=character_page&id=10047358) both are active tonight.  Oneails started I think like 50 minutes before the split, [lasted](http://lineage.onehouronelife.com/server.php?action=character_page&id=10039354&rel_id=10035203) 34 generations, and I think made it to the server merge.  I think there were some other families that started at the split, and lasted until the merge (_so far_... s1 towns are looking stronger as time goes on, I think), though I don't recall all the names.

Edit: I did see failures also.

"That is lower than the pre-influx numbers on bs2, so it's like we got a player exodus instead of a new player wave. "

You're deliberately selecting a custom server!  The wave is still there, you're just not following it, by checking a custom server.  From what I've heard, Twisted has been playing "YOLO" mode and not checking a custom server.

55 players/110 players total on each server for a merge is too high.  Server1 lineages dying out too early would mean that there wouldn't be as much progression in towns.  It's already bad enough that players can't get a child at all sometimes, because no one not checking a custom server is no longer directed to their server (OR because of updates).  Especially since the game gets advertised saying "Have babies of your own in the form of other players" with the idea that one life played only can be sufficient.  Making that even more fragile for players, because they play the game in the default way by not checking a custom server, doesn't sound right.  If anything, the game should cater to players not checking a custom server, and enough of those players will end up on one of the servers later in the list than bigserver2.

Furthermore, the splitting of the servers as it stands basically ensures diversity of town types!  Not every town looks like a diesel water pump town with 3x3 farms and buildings everywhere.  Some do for sure, but other towns actually look and feel different.  New players get to learn the early game more also, since they have that opportunity.  And the problem of scavenging of dead towns and moving items to new places such as loom clothes or steel tools before an iron mine is unlocked (or trucks appearing in a reed skirt tribe... there are so many examples), or worse resettlement, complained about by some veterans, becomes MUCH less of an issue, since scavenging old towns barely happens at all on server1 where there are no trucks that I know of, no paved roads that I know of, etc. and resettling, even if it happens, won't work out as a possibility in all bands.

So far as I can tell also, there isn't an issue with bs2 towns dying out, because of the server split.  [Goda](http://lineage.onehouronelife.com/server.php?action=character_page&id=10049729) family is at 150 generations as I write this, with their Eve having died 3 days ago, thus having lived through at least two, if not three, server splits.  [Kroemer](http://lineage.onehouronelife.com/server.php?action=character_page&id=10017760) family also is 340 generations old.  Their Eve died 6 days ago BEFORE any of the recent server splits.  If memory serves me correctly, [also Content family](http://lineage.onehouronelife.com/server.php?action=character_page&id=8921255), the longest lineage, lived through a few days of server splits.  Bs2 lineages also have more players during low pop hours, because low pop numbers a few weeks ago were in the mid 20s (if not lower).  Bs2, from what I've heard, gets all of the players not checking a custom server, once it's player count hits 29.

Keeping servers split at lower numbers also likely keeps lag issues in check.  And there have existed some reports of strange lag lately.

In conclusion, I see plenty of reasons to keep the server splits and merge as is.  It keeps s1 lineages alive for a reasonable amount of time, makes for more diverse town types and groups for players thus providing more opportunities for them, keeps lag in check to some extent, new players have an opportunity AND REASON to learn the early game (why make a rabbit fur shawl or mouflon hide if you have a loom made shirt that someone imported from 2000 miles away to your Eve camp --- deep well town with their fancy truck?), and there isn't evidence of lineages getting negatively impacted by the server split.

Veterans can easily uncheck playing on a custom server after all.  And the goal isn't just bs2 splitting or only one server, now is it?  It's every last server splitting until they are all full.

**Comment by DougLefelhocz** [comment] 2023-12-30 04:08
Also, it's at least conceivable that some group of people could coordinate and keep a server1 lineage going after a merger period.  If the merger number were higher, then such a group would have to keep that lineage going for a longer period of time.

**Comment by DougLefelhocz** [comment] 2023-12-30 15:38
Also, I found [the forum notes](https://onehouronelife.com/forums/viewtopic.php?id=4930) from what I think was the change to the current system (though the numbers got adjusted later I think).  

"This system was working as intended, but had some unfortunate side-effects on village fertility.  Essentially, if you were on one of the overflow servers during a population downswing, your village was doomed, because no new players would be sent there.  As player population changes throughout the day, this means that various villages die out again and again.  And even worse, other logic in the player distribution code tries to make sure a given player always plays on the same server, whenever possible.  So, depending on the time of the day that you play, and the luck of the draw, you might get stuck always being born on an overflow server right before a population downturn---always playing in a doomed village.

Take a look at the red line (server 4) in this graph, which was generated by Thundersen

...

Villages on server4 were dying out over and over.  Pity the players who were stuck playing on server 4 that evening.

...

Villages on server4 were dying out over and over.  Pity the players who were stuck playing on server 4 that evening."

**Comment by jasonrohrer** [comment] 2024-01-10 17:14
There's no way around preventing people from manually connecting to some server... at least not without major changes and draconian measures.

Essentially, the reflector is what makes these decisions, and the reflector is only used if you autoconnect.  If you manually specify a server, you do connect to that one.

As for keeping the servers split for a long while after, this is intentional, and I don't think there's a better solution.

Let's say you split above 120.  Okay, so now, an hour later, you have 60 on each server.  Now total pop drops to 100, with 50 per server.  Should you unsplit?  Remember, unsplitting means S1 gets no new babies at all, and all the villages there die out.

But what happens an hour after that, when you're back up to 120 and need to split again?  It ping-pongs back and forth between these states.

So we wait until the total player population drops down to 10% of the total active server capacity.

Here are some logs:

```
Dec 26, 2023 09:04:59 PM 130 / 260 >= 0.5 for server bigserver2.onehouronelife.com, starting to spread to next server.
Dec 26, 2023 09:05:08 PM 260 * 0.5 <= 131, 1 servers is not enough, adding another
Dec 27, 2023 06:12:15 AM 660 * 0.1 >= 66, 2 servers is too many, removing one
Dec 27, 2023 07:29:07 PM 260 * 0.5 <= 130, 1 servers is not enough, adding another
Dec 28, 2023 09:01:47 AM 23 / 260 <= 0.1 for server bigserver2.onehouronelife.com, stopping spreading.
Dec 28, 2023 09:02:17 AM 660 * 0.1 >= 66, 2 servers is too many, removing one
Dec 28, 2023 08:14:19 PM 260 * 0.5 <= 130, 1 servers is not enough, adding another
Dec 29, 2023 07:40:07 AM 660 * 0.1 >= 66, 2 servers is too many, removing one
Dec 29, 2023 07:20:30 PM 130 / 260 >= 0.5 for server bigserver2.onehouronelife.com, starting to spread to next server.
Dec 29, 2023 07:39:32 PM 260 * 0.5 <= 130, 1 servers is not enough, adding another
Dec 30, 2023 08:29:11 AM 660 * 0.1 >= 66, 2 servers is too many, removing one
Dec 30, 2023 08:22:31 PM 260 * 0.5 <= 130, 1 servers is not enough, adding another
Dec 31, 2023 07:56:13 AM 660 * 0.1 >= 66, 2 servers is too many, removing one
```

So you can see that the split and unsplit happens about once per day, giving people on both servers ample time to live out their lives across many generations.  This seems okay to me.

**Closed as completed by jasonrohrer** 2024-01-10 17:14 UTC
