### ISSUE TITLE
Sound authorship inconsistencies

### ISSUE THREAD

**Issue by connorhsm** [jasonrohrer/OneLife#1114] opened 2024-07-22 12:35 UTC
In regard to sound authorship for AHAP, I see a number of sounds have an accompanying `.txt` file with the `author=` prefix multiple times. See https://github.com/jasonrohrer/AnotherPlanetData/blob/395f3a1e7b7856f06485b4164ed1a12e2dee2720/sounds/100.txt showing `author=author=author=author=102CA969F5`

I've also added multiple sounds yesterday, but using the `copyChangesToRepo` script has not copied the `.txt` file with my authorship. Or the next sound number file!

**Comment by jasonrohrer** [comment] 2024-08-14 18:19
Aha!  Found the problem here...

So... the problem is in the exporter code, which reads the sound's .txt file, doesn't strip off the author= part, and then adds another author= part when exporting.

**Comment by jasonrohrer** [comment] 2024-08-14 18:24
Also, those sound files with the author= tags can be fixed manually, with a text editor, and then committed.

**Closed as completed by jasonrohrer** 2024-08-14 18:24 UTC
